---
    name: Call Backport Label Updater
    on:
      pull_request:
        types:
          - closed
        branches:
          - v1.13
    jobs:
      call-backport-label-updater:
        if: |
            github.event.pull_request.merged == true &&
            contains(github.event.pull_request.title, 'Backports') &&
            contains(github.event.pull_request.labels.*.name, 'backport/v1.13')
        uses: pippolo84/gh-action-label-test/.github/workflows/update-label-backport-pr.yaml@main
        with:
          pr-body: ${{ github.event.pull_request.body }}
          branch: 1.13
        secrets: inherit
